### ISSUE TITLE
Make alpha optional

### ISSUE THREAD

**Issue by piranna** [JamesMGreene/qunit-assert-canvas#3]
Allow to ignore alpha value

**Comment by JamesMGreene** [comment]
Seems like an easy enough request.

But... why? Is your alpha channel not constant? And, if bothering to verify the canvas's pixels at all, why would you not care about verifying the alpha channel value as well?

I'm OK with making the change regardless of your answer but including some examples of why a user might want to omit the alpha channel on a given assertion would be nice for documenting this variation.

**Comment by piranna** [comment]
I must to say that I've found a workaround so I don't need this anymore :-) The problem was that when unitialized the canvas color is 0,0,0,0 but later when painting something there the alpha channel change to 255, that was annoying me. Maybe it's just enough by documenting this, or maybe not since it's not related to this plugin but the canvas itself... :-P

Anyway, I don't understand why it has an alpha channel at all, since canvas element can't be transparent and if you want to do it you need to use CSS instead, isn't it?

**Comment by JamesMGreene** [comment]
It is possible to change the alpha channel for a canvas without CSS, though a bit clunkier to use than CSS:

http://stackoverflow.com/questions/2359537/how-to-change-the-opacity-alpha-transparency-of-an-element-in-a-canvas-elemen

**Comment by JamesMGreene** [comment]
Updated. Published as `v1.0.3`.

**Comment by piranna** [comment]
Ok, thank you :-)

**Comment by JamesMGreene** [comment]
Welcomed! :+1:
